<?php
/**
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by install script
 * Date: Tue, 11 Aug 2015 12:52:40 +0000
 */
$conf['title'] = 'hireMe Dokumentation';
$conf['lang'] = 'de';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
